set -g default-command "reattach-to-user-namespace -l /bin/zsh"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @dracula-plugins "cpu-usage ram-usage battery network-ping"

set-option -g @pane_resize "2"

set -g mouse on
set-window-option -g mode-keys vi
bind Left swap-window -t -1 \; select-window -t -1
bind Right swap-window -t +1 \; select-window -t +1
set -g renumber-windows on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
