#set -g default-command "reattach-to-user-namespace -l /bin/zsh"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @dracula-plugins "cpu-usage ram-usage battery network-ping"

set-option -g @pane_resize "2"

set -g mouse on
set -g @dracula-show-left-icon session
set-window-option -g mode-keys vi
set -g renumber-windows on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
